[package]
name = "kiln-ir"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true, features = ["rc"] }
serde_json.workspace = true
indexmap.workspace = true
thiserror.workspace = true
sha2.workspace = true
hex.workspace = true
json5.workspace = true
serde_path_to_error.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
