[package]
name = "kiln-wl"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
kiln-ir = { path = "../kiln-ir" }
serde.workspace = true
serde_json.workspace = true
indexmap.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
